server:
  port: 8080

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
  client:
    registryFetchIntervalSeconds: 1
    serviceUrl:
      defaultZone:

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  refresh:
    enabled: true
